apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: backoffice-api
spec:
  # deployment reference
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backoffice-api
  # HPA reference (optional)
  autoscalerRef:
    apiVersion: autoscaling/v2beta2
    kind: HorizontalPodAutoscaler
    name: backoffice-api
  # the maximum time in seconds for the canary deployment
  # to make progress before it is rollback (default 600s)
  progressDeadlineSeconds: 600
  service:
    # ClusterIP port number
    port: 80
    # container port number or name (optional)
    targetPort: 80
    retries:
      attempts: 10
      perTryTimeout: 5s
      retryOn: "gateway-error,connect-failure,refused-stream"    
  analysis:
    # schedule interval (default 60s)
    interval: 30s
    # max number of failed metric checks before rollback
    threshold: 5
    # max traffic percentage routed to canary
    # percentage (0-100)
    maxWeight: 50 
    # canary increment step
    # percentage (0-100)
    stepWeight: 10
    # Linkerd Prometheus checks
    metrics:
    - name: request-success-rate
      # minimum req success rate (non 5xx responses)
      # percentage (0-100)
      thresholdRange:
        min: 99
      interval: 1m
    - name: request-duration
      # maximum req duration P99
      # milliseconds
      thresholdRange:
        max: 200
      interval: 30s
    # testing (optional)
    # webhooks:
    #   - name: acceptance-test
    #     type: pre-rollout
    #     url: http://flagger-loadtester.test/
    #     timeout: 30s
    #     metadata:
    #       type: bash
    #       cmd: "curl -sd 'test' http://podinfo-canary.test:9898/token | grep token"
    #   - name: load-test
    #     type: rollout
    #     url: http://flagger-loadtester.test/
    #     metadata:
    #       cmd: "hey -z 2m -q 10 -c 2 http://podinfo-canary.test:9898/"