apiVersion: apps/v1
kind: Deployment
metadata:
  name: backoffice-api-v1
  labels:
    app: backoffice-api
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backoffice-api
      version: v1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: "52325"
      labels:
        app: backoffice-api
        version: v1
    spec:
      imagePullSecrets:
        - name: azure-acr
      volumes:
      - name: diagnostics
        emptyDir: {}
      containers:
        - name: backoffice-api
          image: tianajoias.azurecr.io/tianajoiasapi:713467946.27
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 100m
              memory: 250Mi
            requests:
              cpu: 100m
              memory: 128Mi
          terminationGracePeriodSeconds: 30
          ports:
            - name: http-port
              containerPort: 80
          volumeMounts:
            - mountPath: /tmp
              name: diagnostics
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: http-port
            initialDelaySeconds: 60
            periodSeconds: 5    
            failureThreshold: 6          
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: http-port
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 6
          envFrom:
            - configMapRef:
                name: backoffice-api
                optional: true
        - name: sidecar
          image: mcr.microsoft.com/dotnet/nightly/monitor:5.0
          volumeMounts:
            - mountPath: /tmp
              name: diagnostics
          ports:
            - containerPort: 52325
          args: ["--urls", "http://*:52323", "--metricUrls", "http://*:52325"]
          livenessProbe:
            httpGet:
              path: /health/ready
              port: 80