apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
   name: backoffice-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backoffice-api
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
    - type: Pods
      pods:
        metric:
          name: http_requests
        target:
          type: AverageValue
          averageValue: 80%