name: BuildPipeline

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - master
  # pull_request:
  #     - master\
env:
  AZURE_WEBAPP_NAME: tianajoiasapi # set this to your application's name
  IMAGE_TAG: ${{ github.run_id }}.${{ github.run_number }}
  IMAGE_NAME_TAG: ${{ secrets.CONTAINER_REGISTRY }}/tianajoiasapi:${{ env.IMAGE_TAG }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Use Node.js
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: 14.x
      # - run: yarn
      # - run: yarn build
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.CONTAINER_REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build -t ${{ env.IMAGE_NAME_TAG }} --label "git-commit=${{ github.sha }}" --label "sourcebranch=${{ github.ref }}" -f Src/WebApi/Dockerfile .  
          docker push ${{ env.IMAGE_NAME_TAG }}
      - uses: cschleiden/replace-tokens@v1
        with:
          files: '["k8s/**/*.yaml"]'
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
      - name: K8s Artifactis
        uses: actions/upload-artifact@v2
        with:
          name: k8s
          path: |
            k8s/**/*.yaml          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: k8s
          path: manifests/artifact   
      - uses: cschleiden/replace-tokens@v1
        with:
          files: '["manifests/artifact/**/*.yaml"]'
        env:
          IMAGE_TAG: ${{ secrets.CONNECTION_STRING }}
      - uses: Azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: contoso
          resource-group: contoso-rg                        
      - uses: azure/k8s-deploy@v1
        with:
          manifests: |
            manifests/deployment.yml
            manifests/service.yml
          images: |
            ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}
          imagepullsecrets: |
            ${{ env.SECRET }}
          namespace: ${{ env.NAMESPACE }}
