name: BackendApi

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - master
  # pull_request:
  #     - master\
env:
  AZURE_WEBAPP_NAME: tianajoiasapi # set this to your application's name
  IMAGE_NAME_TAG: ${{ secrets.CONTAINER_REGISTRY }}/tianajoiasapi:${{ github.run_id }}.${{ github.run_number }}
  SECRET_NAME: azure-acr
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.CONTAINER_REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build -t ${{ env.IMAGE_NAME_TAG }} --label "git-commit=${{ github.sha }}" --label "sourcebranch=${{ github.ref }}" -f Src/WebApi/Dockerfile .  
          docker push ${{ env.IMAGE_NAME_TAG }}
      - name: K8s Manifest
        uses: actions/upload-artifact@v2
        with:
          name: k8s
          path: |
            k8s/**/*.yaml          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
        name: dev
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: k8s
          path: manifests   
      - uses: cschleiden/replace-tokens@v1
        with:
          files: '["manifests/**/*.yaml"]'
        env:
          CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
      - uses: Azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: k8stest
          resource-group: azure-k8stest                 
      - uses: Azure/k8s-create-secret@v1
        with:
          container-registry-url: ${{ secrets.CONTAINER_REGISTRY }}
          container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
          container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          secret-name: demo-k8s-secret          
      - uses: azure/k8s-deploy@v1
        with:
          manifests: |
            manifests/**/*.yml
          images: |
            ${{ env.IMAGE_NAME_TAG }}
          imagepullsecrets: |
            ${{ env.SECRET_NAME }}
          namespace: default
